from "%enlSqGlob/ui/ui_library.nut" import *
let getMissionInfo = require("%enlist/gameModes/getMissionInfo.nut")

let missionsByQueue = {
  enlisted_ussr_ger_low_BR = [
    "volokolamsk_city_assault_ussr", "volokolamsk_city_assault", "volokolamsk_city_bomb", "volokolamsk_city_bomb_ussr", "volokolamsk_city_dom", "volokolamsk_farm_dom", "volokolamsk_forestry_dom", "volokolamsk_forestry_inv_ussr", "volokolamsk_forestry_inv", "volokolamsk_forestry_inv_counter_ussr", "volokolamsk_forestry_inv_counter", "volokolamsk_forestry_bomb", "volokolamsk_forestry_bomb_ussr", "volokolamsk_fortification_dom", "volokolamsk_fortification_inv_ussr", "volokolamsk_fortification_inv", "volokolamsk_grove_dom", "volokolamsk_grove_inv", "volokolamsk_grove_inv_ussr", "volokolamsk_grove_inv_counter", "volokolamsk_grove_inv_counter_ussr", "volokolamsk_grove_conf", "volokolamsk_grove_conf_ussr", "volokolamsk_grove_assault", "volokolamsk_grove_assault_ussr", "volokolamsk_lake_dom", "volokolamsk_lake_inv_ussr", "volokolamsk_lake_inv", "volokolamsk_lake_inv_counter", "volokolamsk_lake_inv_counter_ussr", "volokolamsk_manor_assault_ussr", "volokolamsk_manor_assault", "volokolamsk_manor_dom", "volokolamsk_monastery_dom", "volokolamsk_monastery_inv_ussr", "volokolamsk_monastery_inv", "volokolamsk_monastery_bomb_ussr", "volokolamsk_monastery_bomb", "volokolamsk_quarry_inv_ussr", "volokolamsk_quarry_inv", "volokolamsk_quarry_inv_counter_ussr", "volokolamsk_quarry_inv_counter", "volokolamsk_river_dom", "volokolamsk_village_assault_ussr", "volokolamsk_village_assault", "volokolamsk_village_bomb_ussr", "volokolamsk_village_bomb", "volokolamsk_village_inv_ussr", "volokolamsk_village_inv", "volokolamsk_village_inv_counter", "volokolamsk_village_inv_counter_ussr", "volokolamsk_voskhod_inv", "volokolamsk_voskhod_inv_ussr", "volokolamsk_voskhod_inv_counter", "volokolamsk_voskhod_inv_counter_ussr", "volokolamsk_voskhod_conf", "volokolamsk_voskhod_conf_ussr", "volokolamsk_voskhod_bomb", "volokolamsk_voskhod_bomb_ussr",
  ]
  enlisted_ussr_ger_high_BR = [
    "berlin_chancellery_dom", "berlin_chancellery_conf", "berlin_chancellery_conf_axis", "berlin_chancellery_inv", "berlin_chancellery_inv_axis", "berlin_garden_assault", "berlin_garden_assault_axis", "berlin_garden_bomb", "berlin_garden_bomb_axis", "berlin_garden_inv", "berlin_garden_inv_axis", "berlin_garden_inv_counter", "berlin_garden_inv_counter_allies", "berlin_goering_dom", "berlin_goering_inv", "berlin_goering_inv_axis", "berlin_ministry_inv", "berlin_ministry_inv_counter", "berlin_ministry_conf", "berlin_ministry_conf_axis", "berlin_moat_germany_inv", "berlin_moat_inv_counter", "berlin_opera_assault", "berlin_opera_inv", "berlin_opera_inv_axis", "berlin_station_dom", "berlin_station_inv", "berlin_station_inv_allies", "berlin_station_inv_counter", "berlin_river_inv", "berlin_river_inv_axis", "berlin_river_bomb", "berlin_river_bomb_axis", "berlin_station_bomb", "berlin_station_bomb_axis", "berlin_village_escort_allies", "berlin_village_escort", "berlin_village_dom", "berlin_railway_escort_allies", "berlin_railway_escort", "berlin_bridge_escort_allies", "berlin_bridge_escort", "berlin_bridge_inv", "berlin_bridge_inv_axis", "berlin_railway_conf", "berlin_railway_conf_axis", "berlin_railway_inv", "berlin_railway_inv_axis", "berlin_railway_bomb", "berlin_railway_bomb_axis", "berlin_wilhelm_dom", "berlin_wilhelm_inv",
    "stalingrad_gogol_inv", "stalingrad_gogol_inv_allies", "stalingrad_gogol_inv_counter", "stalingrad_gogol_inv_counter_axis", "stalingrad_gogol_conf", "stalingrad_gogol_conf_allies", "stalingrad_gogol_assault", "stalingrad_gogol_assault_axis", "stalingrad_gogol_assault_counter_axis", "stalingrad_gogol_assault_counter_allies", "stalingrad_univermag_inv", "stalingrad_univermag_inv_axis", "stalingrad_univermag_conf", "stalingrad_univermag_conf_axis", "stalingrad_univermag_inv_counter", "stalingrad_univermag_inv_counter_allies", "stalingrad_communist_inv", "stalingrad_communist_inv_allies", "stalingrad_communist_inv_counter", "stalingrad_communist_inv_counter_axis", "stalingrad_communist_bomb", "stalingrad_communist_bomb_allies", "stalingrad_communist_conf", "stalingrad_communist_conf_allies", "stalingrad_entrance_inv", "stalingrad_entrance_inv_allies", "stalingrad_entrance_inv_counter", "stalingrad_entrance_inv_counter_allies", "stalingrad_entrance_conf", "stalingrad_entrance_conf_allies", "stalingrad_entrance_bomb", "stalingrad_entrance_bomb_allies", "stalingrad_entrance_bomb_counter", "stalingrad_entrance_bomb_counter_allies", "stalingrad_entrance_dom", "stalingrad_station_dom",
  ]
  enlisted_usa_jap_low_BR = [
    "pacific_gavutu_inv", "pacific_gavutu_inv_axis", "pacific_gavutu_inv_counter", "pacific_gavutu_inv_counter_axis", "pacific_gavutu_bomb_aerodrome", "pacific_gavutu_bomb_aerodrome_axis", "pacific_gavutu_bomb", "pacific_gavutu_bomb_axis", "pacific_gavutu_bomb_counter", "pacific_gavutu_bomb_counter_axis", "pacific_gavutu_bomb_aerodrome_counter", "pacific_gavutu_bomb_aerodrome_counter_axis", "pacific_gavutu_conf", "pacific_gavutu_conf_axis", "pacific_gavutu_dom", "pacific_guadalcanal_inv", "pacific_guadalcanal_inv_axis", "pacific_guadalcanal_inv_counter", "pacific_guadalcanal_inv_counter_axis", "pacific_guadalcanal_conf", "pacific_guadalcanal_dom", "pacific_guadalcanal_conf_axis", "pacific_vertical_inv", "pacific_vertical_inv_counter", "pacific_native_inv", "pacific_native_inv_axis", "pacific_new_georgia_coast_inv", "pacific_new_georgia_coast_inv_axis", "pacific_new_georgia_caves_inv", "pacific_new_georgia_caves_inv_axis", "pacific_new_georgia_bomb", "pacific_new_georgia_bomb_axis", "pacific_new_georgia_dom", "pacific_new_georgia_conf", "pacific_new_georgia_conf_axis",
  ]
  enlisted_usa_jap_high_BR = [
    "pacific_gavutu_inv", "pacific_gavutu_inv_axis", "pacific_gavutu_inv_counter", "pacific_gavutu_inv_counter_axis", "pacific_gavutu_bomb_aerodrome", "pacific_gavutu_bomb_aerodrome_axis", "pacific_gavutu_bomb", "pacific_gavutu_bomb_axis", "pacific_gavutu_bomb_counter", "pacific_gavutu_bomb_counter_axis", "pacific_gavutu_bomb_aerodrome_counter", "pacific_gavutu_bomb_aerodrome_counter_axis", "pacific_gavutu_conf", "pacific_gavutu_conf_axis", "pacific_gavutu_dom", "pacific_guadalcanal_inv", "pacific_guadalcanal_inv_axis", "pacific_guadalcanal_inv_counter", "pacific_guadalcanal_inv_counter_axis", "pacific_guadalcanal_conf", "pacific_guadalcanal_dom", "pacific_guadalcanal_conf_axis", "pacific_vertical_inv", "pacific_vertical_inv_counter", "pacific_native_inv", "pacific_native_inv_axis", "pacific_new_georgia_coast_inv", "pacific_new_georgia_coast_inv_axis", "pacific_new_georgia_caves_inv", "pacific_new_georgia_caves_inv_axis", "pacific_new_georgia_bomb", "pacific_new_georgia_bomb_axis", "pacific_new_georgia_dom", "pacific_new_georgia_conf", "pacific_new_georgia_conf_axis",
  ]
  enlisted_usa_ger_low_BR = [
    "tunisia_city_bomb", "tunisia_city_bomb_axis", "tunisia_city_dom", "tunisia_city_conf", "tunisia_city_conf_axis", "tunisia_cave_conf", "tunisia_cave_conf_axis", "tunisia_cave_inv", "tunisia_cave_inv_axis", "tunisia_cave_inv_counter", "tunisia_cave_inv_counter_axis", "tunisia_city_assault", "tunisia_city_assault_axis", "tunisia_city_assault_counter", "tunisia_city_assault_counter_axis", "tunisia_city_inv", "tunisia_city_inv_axis", "tunisia_city_inv_counter", "tunisia_city_inv_counter_axis", "tunisia_farm_assault", "tunisia_farm_assault_axis", "tunisia_farm_bomb", "tunisia_farm_bomb_axis", "tunisia_farm_inv", "tunisia_farm_inv_axis", "tunisia_farm_inv_counter", "tunisia_farm_inv_counter_axis", "tunisia_farm_conf", "tunisia_farm_conf_axis", "tunisia_fortress_inv", "tunisia_fortress_inv_axis", "tunisia_fortress_inv_counter", "tunisia_fortress_inv_counter_axis", "tunisia_gorge_assault", "tunisia_gorge_assault_axis", "tunisia_gorge_bomb", "tunisia_gorge_bomb_axis", "tunisia_gorge_inv", "tunisia_gorge_inv_axis", "tunisia_gorge_inv_counter", "tunisia_gorge_inv_counter_axis", "tunisia_oasis_inv", "tunisia_oasis_inv_axis", "tunisia_oasis_inv_counter", "tunisia_oasis_inv_counter_axis", "tunisia_oasis_dom",
  ]
  enlisted_usa_ger_high_BR = [
    "normandy_aerodrome_inv", "normandy_aerodrome_inv_axis", "normandy_aerodrome_inv_counter", "normandy_aerodrome_inv_counter_axis", "normandy_aerodrome_bomb", "normandy_beach_inv", "normandy_beach_inv_counter", "normandy_city_dom", "normandy_city_inv_allies", "normandy_city_inv", "normandy_city_inv_counter_allies", "normandy_city_inv_counter", "normandy_coast_city_assault", "normandy_coast_city_dom", "normandy_coast_city_inv", "normandy_coast_farm_dom", "normandy_coast_ruins_inv", "normandy_coast_ruins_inv_axis", "normandy_coast_ruins_inv_counter", "normandy_coast_ruins_inv_counter_axis", "normandy_coast_ruins_dom", "normandy_coast_swamp_dom", "normandy_field_dom", "normandy_omer_inv", "normandy_omer_inv_axis", "normandy_omer_inv_counter", "normandy_omer_inv_counter_axis", "normandy_omer_bomb", "normandy_omer_bomb_axis", "normandy_omer_conf", "normandy_omer_conf_axis", "normandy_station_inv", "normandy_station_inv_axis", "normandy_station_inv_counter", "normandy_station_inv_counter_axis", "normandy_station_conf", "normandy_station_conf_axis", "normandy_station_bomb", "normandy_station_bomb_axis", "normandy_village_inv", "normandy_village_inv_axis", "normandy_village_inv_counter", "normandy_village_inv_counter_axis", "normandy_village_bomb", "normandy_village_bomb_axis", "normandy_factory_inv", "normandy_factory_inv_axis", "normandy_factory_inv_counter", "normandy_factory_inv_counter_axis", "normandy_factory_conf", "normandy_factory_conf_axis", "normandy_factory_bomb", "normandy_factory_bomb_axis", "normandy_power_inv", "normandy_power_inv_axis", "normandy_power_inv_counter", "normandy_power_inv_counter_axis", "normandy_power_conf", "normandy_power_conf_axis", "normandy_height_inv", "normandy_height_inv_axis", "normandy_height_inv_counter", "normandy_height_inv_counter_axis", "normandy_height_assault", "normandy_height_assault_axis", "normandy_height_bomb", "normandy_height_bomb_axis", "normandy_height_conf", "normandy_height_conf_axis", "normandy_height_dom", "normandy_forest_inv", "normandy_forest_inv_axis", "normandy_forest_inv_counter", "normandy_forest_inv_counter_axis", "normandy_forest_assault", "normandy_forest_assault_axis", "normandy_forest_bomb", "normandy_forest_bomb_axis", "normandy_forest_conf", "normandy_forest_conf_axis", "normandy_forest_dom",
  ]
  enlisted_ussr_ger_newbies = [
    "volokolamsk_city_assault_ussr", "volokolamsk_city_assault", "volokolamsk_city_bomb", "volokolamsk_city_bomb_ussr", "volokolamsk_city_dom", "volokolamsk_farm_dom", "volokolamsk_forestry_dom", "volokolamsk_forestry_inv_ussr", "volokolamsk_forestry_inv", "volokolamsk_forestry_inv_counter_ussr", "volokolamsk_forestry_inv_counter", "volokolamsk_forestry_bomb", "volokolamsk_forestry_bomb_ussr", "volokolamsk_fortification_dom", "volokolamsk_fortification_inv_ussr", "volokolamsk_fortification_inv", "volokolamsk_grove_dom", "volokolamsk_grove_inv", "volokolamsk_grove_inv_ussr", "volokolamsk_grove_inv_counter", "volokolamsk_grove_inv_counter_ussr", "volokolamsk_grove_conf", "volokolamsk_grove_conf_ussr", "volokolamsk_grove_assault", "volokolamsk_grove_assault_ussr", "volokolamsk_lake_dom", "volokolamsk_lake_inv_ussr", "volokolamsk_lake_inv", "volokolamsk_lake_inv_counter", "volokolamsk_lake_inv_counter_ussr", "volokolamsk_manor_assault_ussr", "volokolamsk_manor_assault", "volokolamsk_manor_dom", "volokolamsk_monastery_dom", "volokolamsk_monastery_inv_ussr", "volokolamsk_monastery_inv", "volokolamsk_monastery_bomb_ussr", "volokolamsk_monastery_bomb", "volokolamsk_quarry_inv_ussr", "volokolamsk_quarry_inv", "volokolamsk_quarry_inv_counter_ussr", "volokolamsk_quarry_inv_counter", "volokolamsk_river_dom", "volokolamsk_village_assault_ussr", "volokolamsk_village_assault", "volokolamsk_village_bomb_ussr", "volokolamsk_village_bomb", "volokolamsk_village_inv_ussr", "volokolamsk_village_inv", "volokolamsk_village_inv_counter", "volokolamsk_village_inv_counter_ussr", "volokolamsk_voskhod_inv", "volokolamsk_voskhod_inv_ussr", "volokolamsk_voskhod_inv_counter", "volokolamsk_voskhod_inv_counter_ussr", "volokolamsk_voskhod_conf", "volokolamsk_voskhod_conf_ussr", "volokolamsk_voskhod_bomb", "volokolamsk_voskhod_bomb_ussr",
  ]
  enlisted_usa_jap_newbies = [
    "pacific_gavutu_inv", "pacific_gavutu_inv_axis", "pacific_gavutu_inv_counter", "pacific_gavutu_inv_counter_axis", "pacific_gavutu_bomb_aerodrome", "pacific_gavutu_bomb_aerodrome_axis", "pacific_gavutu_bomb", "pacific_gavutu_bomb_axis", "pacific_gavutu_bomb_counter", "pacific_gavutu_bomb_counter_axis", "pacific_gavutu_bomb_aerodrome_counter", "pacific_gavutu_bomb_aerodrome_counter_axis", "pacific_gavutu_conf", "pacific_gavutu_conf_axis", "pacific_gavutu_dom", "pacific_guadalcanal_inv", "pacific_guadalcanal_inv_axis", "pacific_guadalcanal_inv_counter", "pacific_guadalcanal_inv_counter_axis", "pacific_guadalcanal_conf", "pacific_guadalcanal_dom", "pacific_guadalcanal_conf_axis", "pacific_vertical_inv", "pacific_vertical_inv_counter", "pacific_native_inv", "pacific_native_inv_axis", "pacific_new_georgia_coast_inv", "pacific_new_georgia_coast_inv_axis", "pacific_new_georgia_caves_inv", "pacific_new_georgia_caves_inv_axis", "pacific_new_georgia_bomb", "pacific_new_georgia_bomb_axis", "pacific_new_georgia_dom", "pacific_new_georgia_conf", "pacific_new_georgia_conf_axis",
  ]
  enlisted_usa_ger_newbies = [
    "tunisia_city_bomb", "tunisia_city_bomb_axis", "tunisia_city_dom", "tunisia_city_conf", "tunisia_city_conf_axis", "tunisia_cave_conf", "tunisia_cave_conf_axis", "tunisia_cave_inv", "tunisia_cave_inv_axis", "tunisia_cave_inv_counter", "tunisia_cave_inv_counter_axis", "tunisia_city_assault", "tunisia_city_assault_axis", "tunisia_city_assault_counter", "tunisia_city_assault_counter_axis", "tunisia_city_inv", "tunisia_city_inv_axis", "tunisia_city_inv_counter", "tunisia_city_inv_counter_axis", "tunisia_farm_assault", "tunisia_farm_assault_axis", "tunisia_farm_bomb", "tunisia_farm_bomb_axis", "tunisia_farm_inv", "tunisia_farm_inv_axis", "tunisia_farm_inv_counter", "tunisia_farm_inv_counter_axis", "tunisia_farm_conf", "tunisia_farm_conf_axis", "tunisia_fortress_inv", "tunisia_fortress_inv_axis", "tunisia_fortress_inv_counter", "tunisia_fortress_inv_counter_axis", "tunisia_gorge_assault", "tunisia_gorge_assault_axis", "tunisia_gorge_bomb", "tunisia_gorge_bomb_axis", "tunisia_gorge_inv", "tunisia_gorge_inv_axis", "tunisia_gorge_inv_counter", "tunisia_gorge_inv_counter_axis", "tunisia_oasis_inv", "tunisia_oasis_inv_axis", "tunisia_oasis_inv_counter", "tunisia_oasis_inv_counter_axis", "tunisia_oasis_dom",
  ]
}

function mkCampaignsByMissions() {
  let missions = {}
  foreach (queueMissions in missionsByQueue) {
    queueMissions.each(function(blk) {
      let { id, campaign } = getMissionInfo(blk)
      missions[id] <- campaign
    })
  }

  return missions
}

return {
  missionsByQueue   // TODO: Should be replaced by information coming in queues from matching,
                    // when it added to queues
  campaignsByMissions = mkCampaignsByMissions()
}